language: rust
rust:
  - stable
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - RUSTFLAGS='-F warnings' cargo build --all
  - cargo test
  - cargo fmt -- --check
stages:
  - Check
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - cargo fmt --all -- --check