language: rust

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt